development:
  adapter: postgresql
  encoding: unicode
  database: myapp_developm
  pool: 5
  username: shaitan
  password: 123456

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_tes
  pool: 5
  username: shaitan
  password: 123456